name: C/C++ CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: sudo apt-get install libpng-dev; cd tests; python ./build.py
