name: Merge master branch to dev
on:
  push:
    branches:
      - 'master'
jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Merge to dev branch
        uses: devmasx/merge-branch@v1.1.0
        with:
          type: now
          target_branch: 'dev'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
